; vim: set ft=asm_ca65 ts=4 sw=4 et:
vdp_ram = $bf30
vdp_reg = $bf31
via_portb       = $BF20
via_porta       = $BF21
via_ddrb        = $BF22
via_ddra        = $BF23
via_t1cl        = $BF24
via_t1ch        = $BF25
via_t1ll        = $BF26
via_t1lh        = $BF27
via_t2cl        = $BF28
via_t2ch        = $BF29
via_sr          = $BF2A
via_acr         = $BF2B
via_pcr         = $BF2C
via_ifr         = $BF2D
via_ier         = $BF2E

